name: Simple Microservice CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Python for test scripts
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install test dependencies
      - name: Install test deps
        run: pip install pytest requests pytest-html

      # 4. Build service docker image
      - name: Build Service
        run: |
          docker build -t sample-service ./dev-service

      # 5. Run service container
      - name: Run container
        run: |
          docker run -d --name sample_service \
            --env-file env/test.env \
            -p 5000:5000 \
            sample-service

          sleep 3

      # 6. Run Tests
      - name: Run Tests
        run: |
          mkdir -p reports
          pytest tests/ --html=reports/test-report.html --self-contained-html

      # 7. Upload Report
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
