name: Simple Microservice CI

on:
  push:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d testing_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing_db

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r dev-service/requirements.txt
          pip install pytest pytest-html pytest-cov requests psycopg2-binary

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      # - name: Wait for PostgreSQL
      #   run: |
      #     echo "Waiting for PostgreSQL to be ready..."
      #     export PGPASSWORD=$POSTGRES_PASSWORD
      #     timeout 60 bash -c 'until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB; do sleep 2; done'
      #     echo "PostgreSQL is ready!"

      - name: Initialize Database
        run: python dev-service/init_db.py

      - name: Run Tests
        run: |
          mkdir -p reports
          pytest tests/ \
            --html=reports/test-report.html \
            --self-contained-html \
            --cov=dev-service \
            --cov-report=xml
        continue-on-error: true

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: reports/

      - name: Send Test Report Email
        uses: dawidd6/action-send-mail@v3
        # if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Test Report"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: "Test report is attached."
          attachments: reports/test-report.html

      - name: Stop Service
        if: always()
        run: |
          docker stop sample_service || true
          docker rm sample_service || true
