name: Simple Microservice CI

on:
  push:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testing_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d testing_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing_db

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r dev-service/requirements.txt
          pip install pytest pytest-html pytest-cov requests psycopg2-binary

      # 4. Wait for Postgres to be ready
      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER
            if [ $? -eq 0 ]; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      # 5. Initialize DB
      - name: Initialize Database
        run: |
          python dev-service/init_db.py

      # 6. Run Tests
      - name: Run Tests
        run: |
          mkdir -p reports
          pytest tests/ \
            --html=reports/test-report.html \
            --self-contained-html \
            --cov=dev-service \
            --cov-report=xml
        continue-on-error: true

      # 7. Upload Test Report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: reports/

      # 8. Send Test Report Email
      - name: Send Test Report Email
        # if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI Test Report"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: "Test report is attached."
          attachments: reports/test-report.html

      - name: Stop Service
        if: always()
        run: |
          docker stop sample_service || true
          docker rm sample_service || true
